language: java
sudo: false # faster builds
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

cache:
  directories:
    - $HOME/.sonar
    - $HOME/.sonarscanner

addons:
  sonarcloud:
    organization: "siatsenko-github"
    token: 0c5602e9a28e70d110b97ca028e0fdd10809fdcf
##      secure: ********* # encrypted value of your token

script:
  - sonar-scanner
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)


