# Configuration for Datasource
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
# for Hikari
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
  cache:
    type: caffeine
    cache-names: cacheGenres
    caffeine:
      spec: expireAfterWrite=30s

# Default mapping for servlet
server:
  servlet:
    context-path: "/v1/"

# Count for random movies
# Doesn't work as "random.count: 3" !!!
randoms:
  count: 3

#Common scheduler
scheduler:
  pool-size: 5

#Scheduled tasks
scheduled:
  # 08 and 16 o'clock of every weekday
  currency:
    cron: "0 0 8,18 * * MON-FRI"

# Currency
currency:
  datePattern: "yyyyMMdd"
  url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange"

# Authentification
auth:
  session:
    # Session timeout 2 hours = 2 * 60 * 60 = 7200 sec.
    timeout: 7200
    # Check session timeout 10 min = 10 * 60 * 1000 = 600000 millisec.
    checkTimeout: 600000

# Spring logging level
logging:
  level:
    root: debug
    org:
      springframwork: debug

#management.security.enabled: false
# for Actuator http://localhost:8080/v1/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# threadPool
threadPool:
  corePoolSize: 0
  maxPoolSize: 50
  keepAliveSec: 60

# SlowService
slowService:
  pause: 5500

# Parallel enrichment
parallelEnrichment:
  timeout: 5000
