# Configuration for Apache DBCP2 Datasource
spring:
  datasource:
    dbcp2:
      defaultAutoCommit: true
      minIdle: 5
      maxIdle: 10
      maxOpenPreparedStatements: 100
      initial-size: 7
      max-total: 20
      pool-prepared-statements: true
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true

# Default mapping for servlet
server:
  servlet:
     context-path: "/v1/"

# Count for random movies
random:
  count: 3

#Common scheduler
scheduler:
  pool-size: 5

#Scheduled tasks
scheduled:
  genre:
    fixedDelay: 14400000
    initialDelay: 14400000
  # 08 and 16 o'clock of every weekday
  currency:
    cron: "0 0 8,18 * * MON-FRI"

# Currency
currency:
  datePattern: "yyyyMMdd"
  url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange"

# Authentification
auth:
  session:
    # Session timeout 2 hours = 2 * 60 * 60 = 7200 sec.
    timeout: 7200
    # Check session timeout 10 min = 10 * 60 * 1000 = 600000 millisec.
    checkTimeout: 600000

# Spring logging level
logging:
  level:
    root: debug
    org:
      springframwork: debug


