# Configuration for Apache DBCP
dbcp2:
  driverClassName: "org.postgresql.Driver"
  url: ${JDBC_DATABASE_URL}
  username: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
  defaultAutoCommit: true
  minIdle: 5
  maxIdle: 10
  maxOpenPreparedStatements: 100
# Count for random movies
random.count: 3
#Common scheduler
scheduler.pool-size: 5
#Scheduled tasks
scheduled:
  genre:
    fixedDelay: 14400000
    initialDelay: 14400000
  currency:
    fixedDelay: 14200000
    initialDelay: 14200000
# Currency
currency:
  datePattern: "yyyyMMdd"
  url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange"